#:schema node_modules/wrangler/config-schema.json
name = "my-app-status"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "app-status-db"
database_id = "6d034d3a-e2d3-4077-a49f-4077127cec7a"
preview_database_id = "6d034d3a-e2d3-4077-a49f-4077127cec7a"